# Generated by Django 6.0.3 on 2026-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_rating_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('bn', 'Bengali')])),
                ('meaning', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
