# Generated by Django 6.0.3 on 2026-04-09 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dictionary_alter_word_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_lyrics', models.TextField()),
                ('hindi_lyrics', models.TextField()),
                ('marathi_lyrics', models.TextField()),
                ('tamil_lyrics', models.TextField()),
                ('bengali_lyrics', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='api.song')),
            ],
        ),
    ]
