# Generated by Django 6.0.3 on 2026-04-10 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_annotationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_entries', to='api.labelsong')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_entries', to='api.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('song__isnull', False), ('label_song__isnull', True)), models.Q(('song__isnull', True), ('label_song__isnull', False)), _connector='OR'), name='favorite_song_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('song__isnull', False)), fields=('user', 'song'), name='unique_user_song_favorite'), models.UniqueConstraint(condition=models.Q(('label_song__isnull', False)), fields=('user', 'label_song'), name='unique_user_label_song_favorite')],
            },
        ),
    ]
