# Generated by Django 6.0.3 on 2026-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_labelsong_audio_file_labelsong_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsong',
            name='tts_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
        migrations.AddField(
            model_name='song',
            name='tts_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
    ]
